[package]
name = "byte-order-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
futures-util = { version = "0.3", features = [ "io" ]}
pin-project-lite = "0.2"